- name: Configure systemd.unified_cgroup_hierarchy=0 in kernelopts
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  notify: Reboot machine
  when: ansible_distribution == "Fedora"