- name: Download Containerlab
  ansible.builtin.get_url:
    url: "{{ clab_download_url }}"
    dest: "/tmp/clab.tar.gz"
    mode: '0644'

- name: Unarchive Containerlab
  ansible.builtin.unarchive:
    src: "/tmp/clab.tar.gz"
    dest: "/tmp"
    remote_src: yes
    mode: '0755'
  ignore_errors: yes

# To store config template files
# https://github.com/srl-labs/containerlab/issues/466
- name: Make sure /etc/containerlab directory exists
  ansible.builtin.file:
    path: "/etc/containerlab"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0755'
  ignore_errors: yes

- name: Copy Containerlab binary
  ansible.builtin.copy:
    src: "/tmp/containerlab"
    dest: "{{ clab_dir }}/containerlab"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: a+x
  ignore_errors: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ clab_dir }}/containerlab"
    dest: "{{ clab_dir }}/clab"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  ignore_errors: yes

- name: Copy Containerlab templates
  ansible.builtin.copy:
    src: "/tmp/templates"
    dest: "/etc/containerlab"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  ignore_errors: yes