# Play 1: Delete AWS resources created (VPC, Subnet, SG, SSH Key Pair, Internet Gateway)
- name: Delete AWS resources
  hosts: localhost
  become: false
  gather_facts: true
  vars_files:
    - ./vars/aws_common.yml

  roles:
      - { role: check_vars }
      - { role: install_dependencies }

  tasks:
    - name: Delete all AWS resources
      ansible.builtin.include_role:
        name: aws_delete_resources