- name: Provision EC2 instance
  community.aws.ec2_instance:
    name: "{{ ec2_name_tag }}"
    region: "{{ ec2_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami_id }}"
    key_name: "{{ ec2_resource_prefix }}-key"
    vpc_subnet_id: "{{ create_subnet.subnet.id }}"
    network:
      assign_public_ip: true
    security_group: "{{ ec2_resource_prefix }}-SG"
    wait: yes
    volumes: "{{ ec2_volume }}"
    tags:
      Environment: "{{ ec2_environment }}"
      DeleteBy: "{{ ec2_delete_by_tag }}"
  register: ec2

- name: Wait for SSH to come up
  include: try-to-ssh.yml
  with_items: "{{ ec2.instances }}"