# Common to all distros
common_software:
  - git
  - wget
  - tree
  - tar
  - python3-pip
  - ansible

# ansible_distribution_file_variety
base_software:
  Debian:
    - dnsutils
    - build-essential
    - python3-dev
  RedHat:
    - bind-utils
    - gcc
    - python3-devel

python_libraries:
- ipaddress

software_additional: []

docker_repo_url: https://download.docker.com/linux